CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers(
	id INTEGER NOT NULL AUTO_INCREMENT,
	burger_name VARCHAR(100) NOT NULL,
	devoured BOOLEAN NOT NULL DEFAULT FALSE,
	date_created  DATETIME DEFAULT CURRENT_TIMESTAMP,
	date_modified DATETIME ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);
